#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT_DIR="${1:-reports/demo-recording}"
ROUNDS="${MEMLINK_DEMO_ROUNDS:-10}"
mkdir -p "$OUT_DIR"
TRANSCRIPT="$OUT_DIR/terminal-demo.txt"
COMMAND_FILE="$OUT_DIR/commands.sh"

cat > "$COMMAND_FILE" <<'SCRIPT'
#!/usr/bin/env bash
set -euo pipefail

echo "# MemLink Rust 2024 demo"
echo "## Workspace"
cargo metadata --no-deps --format-version 1 | python3 -c 'import json,sys; data=json.load(sys.stdin); print("packages=" + ",".join(sorted(p["name"] for p in data["packages"])))'

echo "## Verify tests"
cargo test --workspace

echo "## Run demo"
cargo run -p memlink-cli -- demo --rounds "${MEMLINK_DEMO_ROUNDS:-10}" --output-dir reports/demo

echo "## Audit demo"
cargo run -p memlink-cli -- audit \
  --input-dir reports/demo \
  --min-tasks "${MEMLINK_DEMO_ROUNDS:-10}" \
  --min-state-files 1 \
  --min-memory-hits 1 \
  --min-text-saving "${MEMLINK_MIN_TEXT_SAVING:-0.0}" \
  --min-byte-saving "${MEMLINK_MIN_BYTE_SAVING:-0.0}"

echo "## Report"
sed -n '1,80p' reports/demo/report.md

echo "## Memory search sample"
sed -n '1,80p' reports/demo/memory-search.json

echo "## State files"
find reports/demo/state -type f | sort | sed -n '1,20p'
SCRIPT
chmod +x "$COMMAND_FILE"

rm -rf reports/demo data
"$COMMAND_FILE" 2>&1 | tee "$TRANSCRIPT"

cat > "$OUT_DIR/README.md" <<EOF_README
# MemLink Demo Recording

- Transcript: \`terminal-demo.txt\`
- Commands: \`commands.sh\`
- Rounds: \`$ROUNDS\`

This transcript is generated by \`scripts/record_demo.sh\` and can be used as a video recording guide or submitted as terminal replay evidence when a binary video is not required.
EOF_README

echo "transcript=$TRANSCRIPT"
echo "commands=$COMMAND_FILE"
